name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./root

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # Updated to v3
        with:
          terraform_version: 1.5.0

      # Configure AWS Credentials via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::147997118822:role/GitHubActionsMultiples3Role
          aws-region: us-east-1
          role-session-name: GitHubActionsSession
          role-duration-seconds: 3600

      # Initialize Terraform (sets up S3 backend)
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Optionally apply Terraform changes (only on push to main)
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        environment: production
        run: terraform apply -auto-approve tfplan
